//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace WebApp.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Game
	{
		public string HTML
		{
			get;
			set;
		}

		public string CSS
		{
			get;
			set;
		}

		public string JS
		{
			get;
			set;
		}

		public int GameId
		{
			get;
			set;
		}

		public string UserId
		{
			get;
			set;
		}

		public virtual User User
		{
			get;
			set;
		}

	}
}

