//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó mediante una herramienta.
//     Los cambios del archivo se perderán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------
namespace WebApp.Models
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public partial class User
	{
		public string FirstName
		{
			get;
			set;
		}

		public string LastName
		{
			get;
			set;
		}

		public string Email
		{
			get;
			set;
		}

		public string Phone
		{
			get;
			set;
		}

		public string CellPhone
		{
			get;
			set;
		}

		public bool Gender
		{
			get;
			set;
		}

		public DateTime Birthday
		{
			get;
			set;
		}

		public string Address
		{
			get;
			set;
		}

		public DateTime CreationDate
		{
			get;
			set;
		}

		public virtual IEnumerable<Game> Games
		{
			get;
			set;
		}

	}
}

